apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager # Create it in the cert-manager namespace
type: Opaque
stringData:
  api-token: <1Password pt-br.cloudflare.com>
