# nginx-specific-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-specific-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-specific
  template:
    metadata:
      labels:
        app: nginx-specific
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Simple nginx image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-specific-service
  namespace: default
spec:
  selector:
    app: nginx-specific
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 