---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: appflowy-secrets
  namespace: appflowy
spec:
  itemPath: "vaults/HomeLab6 Systems/items/AppFlowy Secrets"

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: appflowy-pg-cluster-secret
  namespace: appflowy
spec:
  itemPath: "vaults/HomeLab6 Systems/items/appflowy-pg-cluster"
