---
apiVersion: v1
kind: Secret
metadata:
  name: backblaze-b2-secret-backup-target
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_ENDPOINTS: 

---
apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: backblaze-b2-backup
  namespace: longhorn-system
spec:
  backupTargetURL: s3://k8s-longhorn-backup-1@us-east-005/cluster1
  credentialSecret: backblaze-b2-secret-backup-target
  pollInterval: 5m0s 
