---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-i-p-psilva-org-cert
  namespace: uptime-kuma
spec:
  secretName: uptime-kuma-tls
  issuerRef:
    name: letsencrypt-cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "uptime.p.i.psilva.org"
