---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n.p.i.psilva-org-cert
  namespace: n8n
spec:
  secretName: n8n.p.i.psilva-org-tls
  issuerRef:
    name: letsencrypt-cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
  - "n8n.p.i.psilva.org"