apiVersion: v1
kind: Pod
metadata:
  name: nfs-client-reader-pod
spec:
  containers:
    - name: reader
      image: busybox:stable
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: nfs-client-test-pvc


